apiVersion: v1
kind: Service
metadata:
    name: "appweu-ad34"
    labels:
        app: "appweu-ad34"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "appweu-ad34"