# Generated by Django 3.2.8 on 2021-10-12 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_title', models.CharField(max_length=100, verbose_name='Request Title')),
                ('req_type', models.CharField(choices=[('Incident', 'Incident'), ('Create Resource', 'Create Resource'), ('Change Resource', 'Change Resource'), ('Delete Resource', 'Delete Resource')], max_length=50, verbose_name='Request Type')),
                ('req_priority', models.CharField(choices=[('1 - Critical', '1 - Critical'), ('2 - High', '2 - High'), ('3 - Medium', '3 - Medium'), ('4 - Low', '4 - Low')], default='4 - Low', max_length=50, verbose_name='Priority')),
                ('req_sent', models.BooleanField(blank=True, default=False, null=True, verbose_name='GitLab Created')),
                ('req_body', models.TextField(blank=True, null=True, verbose_name='Request Description')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Request',
                'verbose_name_plural': 'Support Requests',
            },
        ),
    ]
