on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: saulweu.azurecr.io
        username: ${{ secrets.acr_saulweu_username }}
        password: ${{ secrets.acr_saulweu_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t saulweu.azurecr.io/appweu:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push saulweu.azurecr.io/appweu:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_appweu_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep app-weu929a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace app-weu929a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: app-weu929a
        container-registry-url: saulweu.azurecr.io
        container-registry-username: ${{ secrets.acr_saulweu_username }}
        container-registry-password: ${{ secrets.acr_saulweu_password }}
        secret-name: appweudockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: app-weu929a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          saulweu.azurecr.io/appweu:${{ github.sha }}
        imagepullsecrets: |
          appweudockerauth
